const axios = require('axios');

// Your API endpoint
const url = 'https://app.instantly.ai/backend/api/v1/analytics/warmup';

// Payload data with email addresses
const accountsEmails = [
    // Add the full list of email addresses here
    "alice@pemaappointments.com",
        "alice@pemafunnels.com",
        "alice@pemagrow.com",
        "alice@pemapipeline.com",
        "alice@pemareach.com",
        "alice@pemascalers.com",
        "alice@pemaset.com",
        "alice@pemasetters.com",
        "alice@pematargets.com",
        "alicej@pemaforward.com",
        "amy@evolution-hce.com",
        "amy@evolutionhomecare.co",
        "amy@evolutionhomecareinc.com",
        "amy@hce-care.com",
        "amy@hcehomecare.com",
        "amy@hcevolutionary.com",
        "amy@homecare-evo-co.com",
        "amy@homecare-evo.com",
        "amy@homecare-evolutionary.com",
        "amy@myhomecareevolution.com",
        "anthony2@anthonytrucks.net",
        "anthony2@clearspeechcoach.com",
        "anthony2@expressfreedomnow.com",
        "anthony2@freedomspeakerpro.com",
        "anthony2@freedomspeakhub.com",
        "anthony2@freedomspeechmentor.com",
        "anthony2@freedomtalkpro.com",
        "anthony2@libertyvoicecoach.com",
        "anthony2@speak2freedom.com",
        "anthony2@speak2freedom.net",
        "anthony2@speakeasyfreedom.com",
        "anthony2@speakfreedomcoach.com",
        "anthony2@speaklibertycoach.com",
        "anthony2@speaktofreedom.ai",
        "anthony2@speaktofreedom.biz",
        "anthony2@speaktofreedom.io",
        "anthony2@speaktofreedom.net",
        "anthony2@speaktofreedomlive.com",
        "anthony2@speaktofreedoms.com",
        "anthony2@vocalizefreedom.com",
        "ashley@anthonytrucks.net",
        "ashley@clearspeechcoach.com",
        "ashley@earningshubhq.com",
        "ashley@expressfreedomnow.com",
        "ashley@freedomspeakerpro.com",
        "ashley@freedomspeakhub.com",
        "ashley@freedomspeechmentor.com",
        "ashley@freedomtalkpro.com",
        "ashley@libertyvoicecoach.com",
        "ashley@speak2freedom.com",
        "ashley@speak2freedom.net",
        "ashley@speakeasyfreedom.com",
        "ashley@speakfreedomcoach.com",
        "ashley@speaklibertycoach.com",
        "ashley@speaktofreedom.ai",
        "ashley@speaktofreedom.biz",
        "ashley@speaktofreedom.net",
        "ashley@speaktofreedomlive.com",
        "ashley@speaktofreedoms.com",
        "ashley@vocalizefreedom.com",
        "audit@createursdesignassoc.com",
        "audit@createursdesignawards.com",
        "bea@realtyresponsepro.com",
        "bridgette@trymoozoom.co",
        "bridgette@trymoozoom.com",
        "brijesh.patel@xemailverify.com",
        "carmen@earningshubhq.com",
        "christine.roque@moozoomapp.com",
        "christine@trymoozoom.co",
        "cindydodd@pema.io",
        "claire@evolution-hce.com",
        "claire@evolutionhomecare.co",
        "claire@evolutionhomecareinc.com",
        "claire@hce-care.com",
        "claire@hcehomecare.com",
        "claire@hcevolutionary.com",
        "claire@homecare-evo-co.com",
        "claire@homecare-evo.com",
        "claire@homecare-evolutionary.com",
        "claire@moozoomapp.com",
        "claire@myhomecareevolution.com",
        "claire@trymoozoom.co",
        "colynn@modernyogateacher.com",
        "courtney@trymoozoom.com",
        "darren.yulfo@haybeach.co",
        "drbaker@expertremedies.com",
        "emma@leadpema.com",
        "emma@leadpemanow.com",
        "emma@leadscalepema.com",
        "emma@pemaadvance.com",
        "emma@pemaclose.com",
        "emma@pemagen.com",
        "emma@pemaleads.com",
        "emma@pemaoutreach.com",
        "emma@pemaprospects.com",
        "emma@pemasales.com",
        "gaby.s@guvfile.co",
        "gaby.s@guvfile.com",
        "gaby.s@guvfile.net",
        "gaby.s@guvfile.org",
        "gaby@guvfile.co",
        "gaby@guvfile.com",
        "gaby@guvfile.net",
        "gaby@guvfile.org",
        "grace@leadpema.com",
        "grace@leadpemanow.com",
        "grace@leadscalepema.com",
        "grace@pemaadvance.com",
        "grace@pemaclose.com",
        "grace@pemagen.com",
        "grace@pemaleads.com",
        "grace@pemaoutreach.com",
        "grace@pemaprospects.com",
        "grace@pemasales.com",
        "hannah@pemaappointments.com",
        "hannah@pemafunnels.com",
        "hannah@pemagrow.com",
        "hannah@pemapipeline.com",
        "hannah@pemareach.com",
        "hannah@pemascalers.com",
        "hannah@pemaset.com",
        "hannah@pemasetters.com",
        "hannah@pematargets.com",
        "hannahw@pemaforward.com",
        "info@guvfile.co",
        "info@guvfile.com",
        "info@guvfile.net",
        "info@guvfile.org",
        "jared@canopyrep.com",
        "kaitlyn.kemper@blueink.marketing",
        "kaitlyn.kemper@blueinkemail.co",
        "kaitlyn.kemper@blueinkemail.org",
        "kaitlyn.kemper@blueinkesignature.co",
        "kaitlyn.kemper@blueinkesignature.com",
        "kaitlyn.kemper@blueinkmarketing.com",
        "kaitlyn@blueink.marketing",
        "kaitlyn@blueinkemail.co",
        "kaitlyn@blueinkemail.com",
        "kaitlyn@blueinkemail.org",
        "kaitlyn@blueinkesignature.co",
        "kaitlyn@blueinkesignature.com",
        "kaitlyn@blueinkmarketing.com",
        "kaitlyn@signblueink.com",
        "kelly@anthonytrucks.net",
        "kelly@clearspeechcoach.com",
        "kelly@expressfreedomnow.com",
        "kelly@freedomspeakerpro.com",
        "kelly@freedomspeakhub.com",
        "kelly@freedomspeechmentor.com",
        "kelly@freedomtalkpro.com",
        "kelly@libertyvoicecoach.com",
        "kelly@speak2freedom.com",
        "kelly@speak2freedom.net",
        "kelly@speakeasyfreedom.com",
        "kelly@speakfreedomcoach.com",
        "kelly@speaklibertycoach.com",
        "kelly@speaktofreedom.biz",
        "kelly@speaktofreedom.io",
        "kelly@speaktofreedom.net",
        "kelly@speaktofreedomlive.com",
        "kelly@speaktofreedoms.com",
        "kelly@vocalizefreedom.com",
        "kk@blueink.marketing",
        "kk@blueinkemail.co",
        "kk@blueinkemail.org",
        "kk@blueinkesignature.com",
        "kk@blueinkmarketing.com",
        "kk@signblueink.com",
        "linda.p@goxemaildeliver.com",
        "linda.p@maildeliveryreport.com",
        "linda.p@runxemaildeliver.com",
        "linda.p@tryxemaildeliver.com",
        "linda.p@tryxemaildeliverlabs.com",
        "linda.p@xemaildeliverlabs.com",
        "linda.patricia@emaildeliverabilitytools.com",
        "linda.patricia@emaildeliveryreport.com",
        "linda.patricia@goxemaildeliver.com",
        "linda.patricia@maildeliveryreport.com",
        "linda.patricia@runxemaildeliver.com",
        "linda.patricia@tryxemaildeliverlabs.com",
        "linda.patricia@xemaildeliverlabs.com",
        "linda.patricia@xemaildeliveryreport.com",
        "linda@maildeliveryreport.com",
        "linda@xemaildeliveryreport.com",
        "lindapatricia@emaildeliveryreport.com",
        "lindapatricia@goxemaildeliver.com",
        "lindapatricia@maildeliveryreport.com",
        "lindapatricia@runxemaildeliver.com",
        "lindapatricia@tryxemaildeliver.com",
        "lindapatricia@tryxemaildeliverlabs.com",
        "lindapatricia@xemaildeliverlabs.com",
        "lindapatricia@xemaildeliveryreport.com",
        "lindsey@eatrollingreens.com",
        "lipatricia@emaildeliveryreport.com",
        "lipatricia@xemaildeliveryreport.com",
        "lpatricia@emaildeliveryreport.com",
        "lucy@pemaappointments.com",
        "lucy@pemafunnels.com",
        "lucy@pemagrow.com",
        "lucy@pemapipeline.com",
        "lucy@pemareach.com",
        "lucy@pemascalers.com",
        "lucy@pemaset.com",
        "lucy@pemasetters.com",
        "lucy@pematargets.com",
        "lucys@pemaforward.com",
        "m.jackness@landlnk.com",
            "mckenzie@trymoozoom.co",
            "michele.j@landlnk.com",
            "michele@landlnk.com",
            "niharika@canopyrep.com",
            "niharika@runxemaildeliver.com",
            "niharika@vidaselect.com",
            "pasquale@trymoozoom.com",
            "patricia.linda@tryxemaildeliver.com",
            "patricia@emaildeliveryreport.com",
            "patriciabm@maildeliveryreport.com",
            "patriciabm@xemaildeliveryreport.com",
            "paula@anthonytrucks.net",
            "paula@clearspeechcoach.com",
            "paula@expressfreedomnow.com",
            "paula@freedomspeakerpro.com",
            "paula@freedomspeakhub.com",
            "paula@freedomspeechmentor.com",
            "paula@freedomtalkpro.com",
            "paula@libertyvoicecoach.com",
            "paula@speak2freedom.com",
            "paula@speakeasyfreedom.com",
            "paula@speakfreedomcoach.com",
            "paula@speaklibertycoach.com",
            "paula@speaktofreedom.ai",
            "paula@speaktofreedom.biz",
            "paula@speaktofreedom.io",
            "paula@speaktofreedom.net",
            "paula@speaktofreedomlive.com",
            "paula@speaktofreedoms.com",
            "paula@vocalizefreedom.com",
            "rf@blueink.email",
            "rocco.freed@blueink.email",
            "rocco@blueink.email",
            "roccof@blueink.email",
            "roney@tradealgo.com",
            "rsophia@blueinkesign.info",
            "rsophia@blueinkesign.net",
            "sarah@leadpema.com",
            "sarah@leadpemanow.com",
            "sarah@leadscalepema.com",
            "sarah@pemaadvance.com",
            "sarah@pemaclose.com",
            "sarah@pemagen.com",
            "sarah@pemaleads.com",
            "sarah@pemaoutreach.com",
            "sarah@pemaprospects.com",
            "sarah@pemasales.com",
            "shivani.yadav@moozoomapp.com",
            "sophia.rose@blueinkesign.info",
            "sophia.rose@blueinkesign.net",
            "sophia@blueinkesign.info",
            "sophia@blueinkesign.net",
            "sophiar@blueinkesign.info",
            "sophiar@blueinkesign.net",
            "sophiarose@blueinkesign.net",
            "timd@pema.io",
            "warmup1@elevateyourempire.net",
            "warmup1@estateconnectcentral.com",
            "warmup1@estateendeavornet.com",
            "warmup1@estateengageconnect.com",
            "warmup1@propertypulselab.co",
            "warmup1@propertypulselab.com",
            "warmup1@propertypulseplus.com",
            "warmup1@realestaterevive.co",
            "warmup1@realtyradarhub.com",
            "warmup1@realtyreachbiz.com",
            "warmup1@realtyreachhub.co",
            "warmup1@realtyreachhub.com",
            "warmup1@realtyreachhub.net",
            "warmup1@realtyresourcebiz.com",
            "warmup1@realtyresponsepro.com",
            "warmup1@realtyresponses.com",
            "warmup1@realtyrisebiz.co",
            "warmup1@realtyrisebiz.com",
            "warmup1@theestateessentials.co",
            "warmup1@theestateessentials.com",
            "warmup@elevateyourempire.net",
            "warmup@estateconnectcentral.com",
            "warmup@estateendeavornet.com",
            "warmup@estateengageconnect.com",
            "warmup@haybeach.co",
            "warmup@haybeachpartners.com",
            "warmup@propertypulselab.co",
            "warmup@propertypulselab.com",
            "warmup@propertypulseplus.com",
            "warmup@realestaterevive.co",
            "warmup@realtyradarhub.com",
            "warmup@realtyreachbiz.com",
            "warmup@realtyreachhub.co",
            "warmup@realtyreachhub.com",
            "warmup@realtyreachhub.net",
            "warmup@realtyresourcebiz.com",
            "warmup@realtyresponsepro.com",
            "warmup@realtyresponses.com",
            "warmup@realtyrisebiz.co",
            "warmup@realtyrisebiz.com",
            "warmup@syftnow.co",
            "warmup@syftnow.com",
            "warmup@theestateessentials.co",
            "warmup@theestateessentials.com",
            "warmup@try-moozoom.co",
            "warmup@try-moozoom.info",
            "warmup@trymoozoom.co",
            "warmup@trymoozoom.com",
            "will@urwstudio.com",
            "william@urwstudio.com",
            "willm@urwstudio.com",
            "xgrowth@goxemaildeliver.com",
            "zoe@evolution-hce.com",
            "zoe@evolutionhomecare.co",
            "zoe@evolutionhomecareinc.com",
            "zoe@hce-care.com",
            "zoe@hcehomecare.com",
            "zoe@hcevolutionary.com",
            "zoe@homecare-evo-co.com",
            "zoe@homecare-evo.com",
            "zoe@homecare-evolutionary.com",
            "zoe@myhomecareevolution.com",
                "anthony@anthonytrucks.net",
                "anthony@clearspeechcoach.com",
                "anthony@expressfreedomnow.com",
                "anthony@freedomspeakerpro.com",
                "anthony@freedomspeakhub.com",
                "anthony@freedomspeechmentor.com",
                "anthony@freedomtalkpro.com",
                "anthony@libertyvoicecoach.com",
                "anthony@speak2freedom.com",
                "anthony@speak2freedom.net",
                "anthony@speakeasyfreedom.com",
                "anthony@speakfreedomcoach.com",
                "anthony@speaklibertycoach.com",
                "anthony@speaktofreedom.ai",
                "anthony@speaktofreedom.io",
                "anthony@speaktofreedom.net",
                "anthony@speaktofreedomlive.com",
                "anthony@speaktofreedoms.com",
                "anthony@vocalizefreedom.com",
                "garber@miniaturemerchandise.com",
                "lakhendra@geteasexpense.com",
                "mahendra.k@geteasexpense.com",
                "mahendra.k@runeasexpense.net",
                "mahendra@geteasexpense.com",
                "mahendra@geteasexpense.net",
                "mahendra@runeasexpense.com",
                "mahendrak@geteasexpense.com",
                "mahendrak@runeasexpense.com",
                "mahendrak@runeasexpense.net",
                "mahi@geteasexpense.net",
                "samantha@miniaturemerchandise.com"
];

// Headers matching those from the browser request
const headers = {
    'Accept': 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'Origin': 'https://app.instantly.ai',
    'Referer': 'https://app.instantly.ai/app/accounts',
    'Sec-Ch-Ua': '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"macOS"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
    'X-Org-Auth': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3X2lkIjoiOTExODU1ZWYtNTgzZC00YWZjLTk1MDktYjIzMjM1MWRhNGY3IiwiaWF0IjoxNzIyMjg4NTczfQ.e_cn5tUJXpLbq_KdFOoeyzLRZR2CIS97THVDCDzJqrc'
};

function chunkArray(array, size) {
    const result = [];
    for (let i = 0; i < array.length; i += size) {
        result.push(array.slice(i, i + size));
    }
    return result;
}

// Make the POST request
async function fetchData() {
    const chunkedEmails = chunkArray(accountsEmails, 50); // Chunk emails in batches of 50
    let finalData = { aggregateData: {}, emailDateData: {} };

    for (const chunk of chunkedEmails) {
        const data = { accountsEmails: chunk };
        try {
            const response = await axios.post(url, data, { headers: headers });
            finalData = {
                aggregateData: { ...finalData.aggregateData, ...response.data.aggregateData },
                emailDateData: { ...finalData.emailDateData, ...response.data.emailDateData }
            };
        } catch (error) {
            console.error('Error:', error);
            throw error;
        }
    }

    return finalData;
}

module.exports = { fetchData };
